site_name: GISBoost
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Montserrat
    code: Roboto Mono
  logo: assets/icon_gisboost.png
  favicon: assets/favicon.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: green
      accent: light blue
  
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: green
      accent: light blue
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    #- navigation.tabs.sticky
    - toc.integrate
    - toc.follow
    - content.code.copy



markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.blocks.caption


extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@GISBoost/
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/michal-kaczorowsky/

nav:
  - Strona główna: index.md
  - O mnie: strona-1.md
  - Poradniki:
    - OTP: OpenTripPlanner.md
    - 2 strona: strona-2.md 
